name: DAVPy2023
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - statsmodels
  - jupyterlab
  - seaborn
  - ipywidgets
  - pip
  - plotnine
  - altair
  - plotly
  - microfilm
  - pip:
    - openpyxl
    - requests
    #- lckr-jupyterlab-variableinspector
    #- jupyterlab-spellchecker