name: DAVPy2024
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - statsmodels
  - jupyterlab
  - seaborn
  - ipywidgets
  - pip
  - plotnine
  - altair
  - plotly
  - microfilm
  - jupyter-ai
  - pip:
    - openpyxl
    - requests
    #- lckr-jupyterlab-variableinspector
    #- jupyterlab-spellchecker
